### ISSUE TITLE
install step missing upload-release arg

### ISSUE THREAD

**Issue by randomtask1155** [pivotal-cf/docs-addon-antivirus#27]
typo in bosh v2 command in step #3 `Upload your release, specifying the path to the tarballed ClamAV binary. For example`
https://docs.pivotal.io/addon-antivirus/1-3/index.html#bosh-cli-v2

command should be

```
$ bosh2 -e my-env upload-release clamav-release.tar.gz
```

**Comment by jncd** [comment]
@randomtask1155 Thanks very much for reporting this.
Should be fixed now.

**Comment by randomtask1155** [comment]
LGTM
