### ISSUE TITLE
Created a first draft of troubleshooting page.

### ISSUE THREAD

**Issue by johnpfield** [pivotal-cf/docs-addon-antivirus#4]
This is a WIP, and still incomplete, but I thought it is worth pushing the branch so that others can contribute to it.  Not making a pull request yet because the work is still in progress.  

The sec-eng-pci team will continue with this, and then we'll issue a pull request against master when it's ready.  

@jncd @oozie

**Comment by animatedmax** [comment]
Accepted 21 Oct 2016
